# Generated by Django 5.0.1 on 2024-02-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
