# Generated by Django 5.0.1 on 2024-02-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
